---
- name: install apache server
  hosts: all
  become: yes

  tasks:
  - name: install apache is the latest version
    yum:
      name: httpd
      state: latest
  - name: start apache service
    service:
      name: httpd
      state: started
